name: hello-fromhexlet
on: push
jobs:
  hello-from-hexlet-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Print Hello from Hexlet
        uses: hexlet-components/hello-from-hexlet-action@release
